import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Analytics & Reporting | Real-Time SEO Dashboard & Keyword Ranking Tracker | SEO Automation",
  description: "Comprehensive SEO analytics dashboard with real-time keyword ranking tracker, traffic monitoring, indexing status, and automated reporting. Google Search Console and Analytics integration provides 50K+ keyword tracking, 10M+ monthly impressions analysis, 24-month historical data, competitor rankings, Core Web Vitals monitoring, and white-label PDF reports for agencies. Make data-driven SEO decisions with unified dashboard eliminating manual exports. Track rankings daily at 2 AM UTC, high-priority keywords every 6 hours, GSC sync every 4 hours. Custom dashboards for stakeholders with drag-and-drop widgets. Export reports in PDF, Excel, CSV. OAuth 2.0 security with read-only permissions, SOC 2 Type II certified.",
  keywords: [
    "seo analytics dashboard",
    "seo analytics",
    "search analytics",
    "seo reporting tool",
    "seo dashboard",
    "keyword ranking tracker",
    "keyword position tracker",
    "ranking tracker",
    "real-time seo analytics",
    "seo performance tracking",
    "seo metrics dashboard",
    "traffic analytics",
    "indexing status monitor",
    "seo reporting software",
    "automated seo reports",
    "white label seo reports",
    "branded seo reports",
    "pdf seo reports",
    "client reporting",
    "agency reporting",
    "google search console integration",
    "gsc integration",
    "google analytics integration",
    "ga4 integration",
    "search console data",
    "traffic monitoring",
    "ctr analysis",
    "click through rate analysis",
    "impression tracking",
    "organic traffic analytics",
    "search traffic analysis",
    "keyword position tracking",
    "daily rank tracking",
    "ranking updates",
    "position monitoring",
    "serp tracking",
    "search engine ranking",
    "ranking changes",
    "position history",
    "keyword rankings",
    "indexing coverage",
    "index status monitor",
    "crawl errors tracking",
    "sitemap monitoring",
    "crawl budget tracking",
    "core web vitals tracking",
    "lcp monitoring",
    "fid tracking",
    "cls monitoring",
    "page speed metrics",
    "mobile usability",
    "technical seo audit",
    "competitor ranking tracker",
    "competitor analysis",
    "competitive analysis",
    "keyword gap analysis",
    "competitor monitoring",
    "serp competitor tracking",
    "historical seo data",
    "24 month history",
    "ranking history",
    "traffic trends",
    "seo trend analysis",
    "custom seo dashboards",
    "dashboard widgets",
    "stakeholder dashboards",
    "executive seo reports",
    "detailed seo analysis",
    "seo data visualization",
    "analytics charts",
    "ranking charts",
    "traffic graphs",
    "automated report scheduling",
    "scheduled reports",
    "weekly seo reports",
    "monthly seo reports",
    "report automation",
    "api access analytics",
    "rest api seo data",
    "webhook alerts",
    "seo alerts",
    "ranking alerts",
    "traffic drop alerts",
    "indexing alerts",
    "data export",
    "csv export seo",
    "excel export analytics",
    "json export",
    "bulk data export",
    "oauth security",
    "google oauth",
    "secure seo analytics",
    "encrypted data",
    "soc 2 compliance",
    "gdpr compliant analytics",
    "read-only access",
    "50k keywords",
    "keyword capacity",
    "enterprise analytics",
    "saas seo analytics"
  ],
  openGraph: {
    title: "Analytics & Reporting | Real-Time SEO Dashboard & Keyword Ranking Tracker",
    description: "Real-time SEO analytics dashboard with 50K+ keyword tracking, Google Search Console integration, traffic monitoring, indexing status, automated reporting, and white-label PDF exports for agencies. Track rankings daily, monitor Core Web Vitals, create custom dashboards for stakeholders.",
    type: "website",
    images: [
      {
        url: "/og-analytics-reporting.png",
        width: 1200,
        height: 630,
        alt: "SEO Analytics & Reporting Dashboard - Real-Time Keyword Rankings, Traffic Monitoring, Automated Reports"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title: "Analytics & Reporting | SEO Dashboard & Keyword Tracker",
    description: "Real-time SEO analytics: 50K+ keyword tracking, GSC/GA integration, traffic monitoring, indexing status, automated PDF reports. Make data-driven decisions with unified dashboard.",
    images: ["/og-analytics-reporting.png"]
  },
  alternates: {
    canonical: "https://seoautomation.com/features/analytics-reporting"
  }
};

export default function AnalyticsReportingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
